import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  const [del, result] = await Promise.all([
    knex("V_Minha_Regulacao").del(),
    knex("V_Minha_Regulacao").insert([
      {
        Paciente: "João Silva",
        DescMotivoSol: "Dor de cabeça",
        DataAbre: "2022-01-01",
        DataNasc: "1997-01-01",
        DataRealiza: "2022-01-01",
        Município: "São Paulo",
        NmStatusOcorr: "Em atendimento",
      },
      {
        Paciente: "Maria Oliveira",
        DescMotivoSol: "Manchas na pele",
        DataAbre: "2022-02-01",
        DataNasc: "1996-01-01",
        DataRealiza: "2022-02-01",
        Município: "Rio de Janeiro",
        NmStatusOcorr: "Concluído",
      },
      {
        Paciente: "Carlos Gomes",
        DescMotivoSol: "Dor de barriga",
        DataAbre: "2022-03-01",
        DataNasc: "1995-01-01",
        DataRealiza: "2022-03-01",
        Município: "Belo Horizonte",
        NmStatusOcorr: "Em atendimento",
      },
      {
        Paciente: "Ana Paula",
        DescMotivoSol: "Tontura",
        DataAbre: "2022-04-01",
        DataNasc: "1994-01-01",
        DataRealiza: "2022-04-01",
        Município: "Porto Alegre",
        NmStatusOcorr: "Concluído",
      },
      {
        Paciente: "Pedro Soares",
        DescMotivoSol: "Dor de ouvido",
        DataAbre: "2022-05-01",
        DataNasc: "1993-01-01",
        DataRealiza: "2022-05-01",
        Município: "Curitiba",
        NmStatusOcorr: "Em atendimento",
      },
      {
        Paciente: "Juliana Ferreira",
        DescMotivoSol: "Dor de cabeça",
        DataAbre: "2022-06-01",
        DataNasc: "1992-01-01",
        DataRealiza: "2022-06-01",
        Município: "Salvador",
        NmStatusOcorr: "Concluído",
      },
      {
        Paciente: "Lucas Alves",
        DescMotivoSol: "Manchas na pele",
        DataAbre: "2022-07-01",
        DataNasc: "1991-01-01",
        DataRealiza: "2022-07-01",
        Município: "Fortaleza",
        NmStatusOcorr: "Em atendimento",
      },
      {
        Paciente: "Isabela Costa",
        DescMotivoSol: "Dor de barriga",
        DataAbre: "2022-08-01",
        DataNasc: "1990-01-01",
        DataRealiza: "2022-08-01",
        Município: "Recife",
        NmStatusOcorr: "Concluído",
      },
      {
        Paciente: "Rafael Lima",
        DescMotivoSol: "Dor de dente",
        DataAbre: "2022-09-01",
        DataNasc: "1989-01-01",
        DataRealiza: "2022-09-01",
        Município: "Belém",
        NmStatusOcorr: "Em atendimento",
      },
      {
        Paciente: "Gabriela Souza",
        DescMotivoSol: "Tontura",
        DataAbre: "2022-10-01",
        DataNasc: "1988-01-01",
        DataRealiza: "2022-10-01",
        Município: "Manaus",
        NmStatusOcorr: "Concluído",
      },
      {
        Paciente: "Caio Santos",
        DescMotivoSol: "Manchas na pele",
        DataAbre: "2022-11-01",
        DataNasc: "1985-01-01",
        DataRealiza: "2022-11-01",
        Município: "João Pessoa",
        NmStatusOcorr: "Em atendimento",
      },
      {
        Paciente: "Vitor Silva",
        DescMotivoSol: "Dor de ouvido",
        DataAbre: "2022-12-01",
        DataNasc: "1987-01-01",
        DataRealiza: "2022-12-01",
        Município: "São Luís",
        NmStatusOcorr: "Concluído",
      },
      {
        Paciente: "Larissa Albuquerque",
        DescMotivoSol: "Dor de cabeça",
        DataAbre: "2022-12-01",
        DataNasc: "1986-01-01",
        DataRealiza: "2022-12-01",
        Município: "Belo Horizonte",
        NmStatusOcorr: "Em atendimento",
      },
      {
        Paciente: "Caio Santos",
        DescMotivoSol: "Dor de ouvido",
        DataAbre: "2023-01-01",
        DataNasc: "1985-01-01",
        DataRealiza: "2023-01-01",
        Município: "João Pessoa",
        NmStatusOcorr: "Concluído",
      },
    ]),
  ]);

	console.log("Dados Removidos", del)
}
